### PR TITLE
Make memory size portable on both 32/64-bit target

### LINKED ISSUE #161: Non-portable memory allocation
There is a non-portable issue in `src/io.c`:
```c
/* set memory size to 2^32 bytes */
#define MEM_SIZE 0x100000000ULL
```

If we are building with [Emscripten](https://emscripten.org/) (see also #75), 32-bit target is [set by default](https://github.com/emscripten-core/emscripten/issues/19833), and the clang would complain as following:
```
src/io.c:27:35: warning: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned long') changes value from 4294967296 to 0 [-Wconstant-conversion]
   27 |     data_memory_base = mmap(NULL, MEM_SIZE, PROT_READ | PROT_WRITE,
      |                        ~~~~       ^~~~~~~~
src/io.c:21:18: note: expanded from macro 'MEM_SIZE'
   21 | #define MEM_SIZE 0x100000000ULL
      |                  ^~~~~~~~~~~~~~
src/io.c:43:27: warning: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned long') changes value from 4294967296 to 0 [-Wconstant-conversion]
   43 |     munmap(mem->mem_base, MEM_SIZE);
      |     ~~~~~~                ^~~~~~~~
src/io.c:21:18: note: expanded from macro 'MEM_SIZE'
   21 | #define MEM_SIZE 0x100000000ULL
      |                  ^~~~~~~~~~~~~~
```

rv32emu should be portable for both 32-bit and 64-bit environments. Therefore, we need to address the improper memory allocation issue that has been raised on 32-bit targets.

### PR DESCRIPTION
**Pull request by ChinYikMing**
Close #161

### CODE REVIEW

**Comment by jserv** [comment]
@ChinYikMing, Quick tip for submitting pull requests: when creating branches for your changes, consider using branch names other than `master`. This practice allows you to keep the master branch up to date and enables the proposed branches associated with pull requests to be easily rebased when needed.

**Comment by jserv** [comment]
@qwe661234, An empirical approach is necessary to specify the limits, including memory size in this case. Can you do that?

**Comment by qwe661234** [comment]
> @qwe661234, An empirical approach is necessary to specify the limits, including memory size in this case. Can you do that?

In my opinion, we can modify memory size to `0xFFFFFFFF` without checking data model. This memory size works in both 32-bit and 64-bit machine. Actually, the data memory usage of most test cases would not reach `0xFFFFFFFF`.

**Comment by jserv** [comment]
@ChinYikMing, If you would like to close an issue, there must be an evident reason.

**Comment by ChinYikMing** [comment]
My bad, I accidentally fetch and sync the upstream thus make this PR closed. I think the opinion of @qwe661234 is good since all test cases would not reach there for now. Shall I push another PR for closing this issue?

**Comment by jserv** [comment]
> My bad, I accidentally fetch and sync the upstream thus make this PR closed. I think the opinion of @qwe661234 is good since all test cases would not reach there for now. Shall I push another PR for closing this issue?

Up to you. You can either reopen this pull request or create a new one. Next time, be aware of git history (the DAG).

**Pull request closed without merging**
