### PR TITLE
CI: Fix error when running on host-arm64

### LINKED ISSUE #502: No match for platform in manifest: not found on host-arm64
CI on host-arm64 fails during this [action](https://github.com/sysprog21/rv32emu/actions/runs/11415766801). Based on issues [1] of the `run-on-arch-action` script, the `base_image` option can be useful. When utilizing `base_image`, we should specify the `--platform`, and set both the `distro` and `arch` to `none` [2].

```
with:
    arch: none
    distro: none
    base_image: "--platform=linux/arm64 arm64v8/ubuntu:22.04"
```

The original `arch` and `distro` manner could be reused once PR[3] or other related works are merged. 

Tested on [action](https://github.com/ChinYikMing/rv32emu/actions/runs/11416988476).

Reference:
[1] [No match for platform in manifest: not found](https://github.com/uraimo/run-on-arch-action/issues/154), [fedora_latest for other arches](https://github.com/uraimo/run-on-arch-action/issues/152#issuecomment-2401981347)
[2] [README](https://github.com/uraimo/run-on-arch-action?tab=readme-ov-file#usage)
[3] [Pass arch value to --platform](https://github.com/uraimo/run-on-arch-action/pull/153)

### PR DESCRIPTION
**Pull request by ChinYikMing**
Close #502

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Improve the git commit message to address the rationale of the proposed changes. What confuses me is the entry in arm64 host.

**Comment by ChinYikMing** [comment]
When trying to run `arm64v8/ubuntu:22.04` on a x86 machine, the following similar result will be shown:
```
$ docker run -it arm64v8/ubuntu:22.04
Unable to find image 'arm64v8/ubuntu:22.04' locally
22.04: Pulling from arm64v8/ubuntu
docker: no matching manifest for linux/amd64 in the manifest list entries.
```

**Comment by jserv** [comment]
> When trying to run `arm64v8/ubuntu:22.04` on a x86 machine, the following similar result will be shown:

So, will the proposed change work with Docker?

**Comment by ChinYikMing** [comment]
> > When trying to run `arm64v8/ubuntu:22.04` on a x86 machine, the following similar result will be shown:
> 
> So, will the proposed change work with Docker?

Yes, the proposed change ensures that the Docker engine uses the appropriate manifest when pulling the base image.

**Comment by jserv** [comment]
Thank @ChinYikMing for contributing!

**Pull request merged**
