### PR TITLE
Fix csrrwi instruction behavior according to risc-v spec

### PR DESCRIPTION
**Pull request by feathertw**

### CODE REVIEW

**Comment by jserv** [comment]
Can you quote from RISC-V privileged instruction in git commit message? The instruction format should be mentioned and explained. You don't have to re-create the new issues. Instead, use `git commit --amend` to rework and then do `git push --force`.

**Comment by jserv** [comment]
Also, append `Close #7` at the end of git commit message.

**Comment by feathertw** [comment]
I add more information into the commit log and then `git push -f` it

**Review by jserv — CHANGES_REQUESTED** [review]
Please read this carefully: https://dev.to/thelogeshwaran/how-to-write-good-commit-messages-714
* Wrap lines at 72 characters

Don't mention "Issue #7" in the subject of git commit message.

**Comment by jserv** [comment]
Thank @feathertw for contributing!

**Comment by feathertw** [comment]
My pleasure!

**Pull request merged**
