### PR TITLE
CI: Generate Docker image with Alpine Linux

### LINKED ISSUE #286: CI: Generate Docker image with Alpine Linux
Currently, the CI pipeline can generate Docker images, but the size of these images is quite large, which is not ideal for showcasing a small yet powerful RISC-V instruction set simulator. To address this, we can consider rebuilding the Docker image using [Alpine Linux](https://www.alpinelinux.org/), a security-focused, lightweight Linux distribution that uses musl libc and busybox. This would not only reduce the image size but also provide a minimal runtime environment.

### PR DESCRIPTION
**Pull request by henrybear327**
Close #286

### CODE REVIEW

**Comment by henrybear327** [comment]
With this current change, I observed that the image size reduced from 96 MB to 12.4 MB. 

However, the `rv32emu` will return a `segmentation fault` by executing any of the `elf` files provided in the `build` directory. The root cause to be investigated.

**Comment by henrybear327** [comment]
> With this current change, I observed that the image size reduced from 96 MB to 12.4 MB.
> 
> However, the `rv32emu` will return a `segmentation fault` by executing any of the `elf` files provided in the `build` directory. The root cause to be investigated.

The current PR works on `node11`, both building the image and executing `rv32emu`. 

However, it doesn't work on my Intel MacBook. I currently don't have a M1 laptop at hand, can @jserv help me quickly test it out?

The testing can be performed as shown:
- build the docker image: `docker build --progress=plain -t rv32emu-slim .`
- spin up a container: `docker run -it rv32emu-slim`
- execute a elf file: `rv32emu ./build/hello.elf`

**Comment by jserv** [comment]
> The testing can be performed as shown:
> * build the docker image: `docker build --progress=plain -t rv32emu-slim .`
> * spin up a container: `docker run -it rv32emu-slim`
> * execute a elf file: `rv32emu ./build/hello.elf`

Due to Docker being cumbersome and resource-intensive on macOS with Apple Silicon, I prefer using [nerdctl](https://github.com/containerd/nerdctl), which offers a command line interface that is compatible with Docker.

Along with [lima](https://github.com/lima-vm/lima), I run the command `nerdctl.lima build --progress=plain -t rv32emu-slim .` and the following message appears:
```
#11 [base_gcc 6/6] RUN make tool
#11 0.144   CC	build/rv_histogram.o
#11 0.232   LD	build/rv_histogram
#11 0.240 build/riscv.o: file not recognized: file format not recognized
#11 0.240 collect2: error: ld returned 1 exit status
#11 0.241 make: *** [mk/tools.mk:24: build/rv_histogram] Error 1
#11 ERROR: process "/bin/sh -c make tool" did not complete successfully: exit code: 2
```

**Comment by henrybear327** [comment]
> > The testing can be performed as shown:
> > 
> > * build the docker image: `docker build --progress=plain -t rv32emu-slim .`
> > * spin up a container: `docker run -it rv32emu-slim`
> > * execute a elf file: `rv32emu ./build/hello.elf`
> 
> Due to Docker being cumbersome and resource-intensive on macOS with Apple Silicon, I prefer using [nerdctl](https://github.com/containerd/nerdctl), which offers a command line interface that is compatible with Docker.
> 
> Along with [lima](https://github.com/lima-vm/lima), I run the command `nerdctl.lima build --progress=plain -t rv32emu-slim .` and the following message appears:
> 
> ```
> #11 [base_gcc 6/6] RUN make tool
> #11 0.144   CC	build/rv_histogram.o
> #11 0.232   LD	build/rv_histogram
> #11 0.240 build/riscv.o: file not recognized: file format not recognized
> #11 0.240 collect2: error: ld returned 1 exit status
> #11 0.241 make: *** [mk/tools.mk:24: build/rv_histogram] Error 1
> #11 ERROR: process "/bin/sh -c make tool" did not complete successfully: exit code: 2
> ```

Things are getting interesting, as I can't reproduce this error.

**Comment by henrybear327** [comment]
> > With this current change, I observed that the image size reduced from 96 MB to 12.4 MB.
> > However, the `rv32emu` will return a `segmentation fault` by executing any of the `elf` files provided in the `build` directory. The root cause to be investigated.
> 
> The current PR works on `node11`, both building the image and executing `rv32emu`.
> 
> However, it doesn't work on my Intel MacBook. I currently don't have a M1 laptop at hand, can @jserv help me quickly test it out?
> 
> The testing can be performed as shown:
> 
> * build the docker image: `docker build --progress=plain -t rv32emu-slim .`
> * spin up a container: `docker run -it rv32emu-slim`
> * execute a elf file: `rv32emu ./build/hello.elf`

After running `strace`, we got 
```
/home/root/rv32emu # strace rv32emu ./build/hello.elf 
execve("/home/root/rv32emu/build/rv32emu", ["rv32emu", "./build/hello.elf"], 0x7ffd9792b7b8 /* 5 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f8c307a1b08) = 0
set_tid_address(0x7f8c307a1f70)         = 20
brk(NULL)                               = 0x5604471ca000
brk(0x5604471cc000)                     = 0x5604471cc000
mmap(0x5604471ca000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x5604471ca000
mprotect(0x7f8c3079e000, 4096, PROT_READ) = 0
mprotect(0x560445d43000, 4096, PROT_READ) = 0
open("build/hello.elf", O_RDONLY|O_LARGEFILE) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=4812, ...}) = 0
mmap(NULL, 4812, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8c306fe000
close(3)                                = 0
mmap(NULL, 4294967295, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Out of memory)
mmap(NULL, 49152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8c306f2000
mmap(NULL, 73728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8c306e0000
mmap(NULL, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8c306d9000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

As my docker/lima was configured to allocate only 4GiB of memory in the container, `mmap` failed with OOM. After increasing the memory allocation to 8GiB, the code runs smoothly. 

After checking the source code, maybe we need to mention this in README as a hardware requirement?
```
/*
 * set memory size to 2^32 - 1 bytes
 *
 * The memory size is set to 2^32 - 1 bytes in order to make this emulator
 * portable for both 32-bit and 64-bit platforms. As a result, it can access
 * any segment of the memory on either platform. Furthermore, it is safe
 * because most of the test cases' data memory usage will not exceed this
 * memory size.
 */
#define MEM_SIZE 0xFFFFFFFFULL
```

**Comment by henrybear327** [comment]
> > The testing can be performed as shown:
> > 
> > * build the docker image: `docker build --progress=plain -t rv32emu-slim .`
> > * spin up a container: `docker run -it rv32emu-slim`
> > * execute a elf file: `rv32emu ./build/hello.elf`
> 
> Due to Docker being cumbersome and resource-intensive on macOS with Apple Silicon, I prefer using [nerdctl](https://github.com/containerd/nerdctl), which offers a command line interface that is compatible with Docker.
> 
> Along with [lima](https://github.com/lima-vm/lima), I run the command `nerdctl.lima build --progress=plain -t rv32emu-slim .` and the following message appears:
> 
> ```
> #11 [base_gcc 6/6] RUN make tool
> #11 0.144   CC	build/rv_histogram.o
> #11 0.232   LD	build/rv_histogram
> #11 0.240 build/riscv.o: file not recognized: file format not recognized
> #11 0.240 collect2: error: ld returned 1 exit status
> #11 0.241 make: *** [mk/tools.mk:24: build/rv_histogram] Error 1
> #11 ERROR: process "/bin/sh -c make tool" did not complete successfully: exit code: 2
> ```

Maybe some object files are copied from the folder directly during the build. Can you try to run `make clean` before building the container? 

Thank you!

**Comment by jserv** [comment]
> Maybe some object files are copied from the folder directly during the build. Can you try to run `make clean` before building the container?

Additional `make distclean` is required. It proceeds now.

**Pull request merged**
