### PR TITLE
build/quake: Lower resolution to speed up game execution

### PR DESCRIPTION
**Pull request by Korin777**
change resolution from 800x480 to 400x240, speed up from 15s/frame to 7s/frame

### CODE REVIEW

**Comment by jserv** [comment]
You should make use of `git rebase -i` to rework the commits. Only single commit is required.

**Comment by jserv** [comment]
You should run `strip` (in fact, `riscv-none-embed-strip -s`) to get smaller ELF executable file.

**Comment by Korin777** [comment]
> You should make use of `git rebase -i` to rework the commits. Only single commit is required.

I am trying to use it

**Comment by Korin777** [comment]
> You should run `strip` (in fact, `riscv-none-embed-strip -s`) to get smaller ELF executable file.

If I use riscv-none-embed-strip -s or riscv64-unknown-elf-strip -s to quake or doom, the game will not display when runing on rv32emu-next, it seems the program stuck in somwhere。

**Comment by jserv** [comment]
> If I use riscv-none-embed-strip -s or riscv64-unknown-elf-strip -s to quake or doom, the game will not display when runing on rv32emu-next, it seems the program stuck in somwhere。

It would be great if we can look into this later.

**Review by jserv — CHANGES_REQUESTED** [review]
Run resolve the conflicts and do `git push --force`

**Pull request merged**
