### PR TITLE
Remove extra comma of SUPPORTED_SYSCALLS

### PR DESCRIPTION
**Pull request by huaxinliao**

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Read https://cbea.ms/git-commit/ and refine the subject of this pull request and git commit message.

**Comment by jserv** [comment]
There was no grammar error though.

**Comment by huaxinliao** [comment]
Sorry, I would take time to refine the subject of this pull request and git commit message.

**Comment by huaxinliao** [comment]
I have completed my modifications.

**Comment by jserv** [comment]
> I have completed my modifications.

You don't have to leave a message like this. GitHub would automatically notify the subscribers.

**Comment by jserv** [comment]
Thank @p96114175 for contributing!

**Pull request merged**
