### PR TITLE
CI: Bump riscv-gnu-toolchain

### PR DESCRIPTION
**Pull request by jserv**
Nightly Release: [April 12, 2024](https://github.com/riscv-collab/riscv-gnu-toolchain/releases/tag/2024.04.12)

### CODE REVIEW

**Comment by henrybear327** [comment]
We might also want to bump the [reference device binary](https://github.com/sysprog21/rv32emu/blob/master/tests/arch-test-target/sail_cSim/riscv_sim_RV32).

**Comment by visitorckw** [comment]
It's weird to see an error message from the assembler. This makes me wonder if it might be a compatibility issue or an error between the upstream toolchain and the riscv-arch-test?

**Comment by vacantron** [comment]
@jserv, I bump `riscv-arch-test` to `ed32d67` also and the error is disappeared. Can you confirm this?

**Comment by visitorckw** [comment]
> @jserv, I bump `riscv-arch-test` to `ed32d67` also and the error is disappeared. Can you confirm this?

FWIW, it resolved the issue in my environment.

Tested-by: Kuan-Wei Chiu \<visitorckw@gmail.com\>

**Comment by visitorckw** [comment]
However, although it no longer encounters assembler errors and runs the compliance test correctly, it fails to pass the test suite for the M and A extensions. Additionally, in the C extension tests, it encounters the following assertion error:
```
rv32emu: src/emulate.c:650: block_translate: Assertion `prev_ir' failed.
Aborted (core dumped)
```

**Comment by jserv** [comment]
> We might also want to bump the [reference device binary](https://github.com/sysprog21/rv32emu/blob/master/tests/arch-test-target/sail_cSim/riscv_sim_RV32).

@vacantron, can you rebuild `tests/arch-test-target/sail_cSim/riscv_sim_RV32` based on the latest [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test) and resolve the potential compliance issues? You can simply update [arch-test](https://github.com/vacantron/rv32emu/tree/arch-test) branch, so that I can cherry-pick git commits.

**Comment by vacantron** [comment]
> However, although it no longer encounters assembler errors and runs the compliance test correctly, it fails to pass the test suite for the M and A extensions. Additionally, in the C extension tests, it encounters the following assertion error:
> ```
> rv32emu: src/emulate.c:650: block_translate: Assertion `prev_ir' failed.
> Aborted (core dumped)
> ```

AFAIK, this error might happen when configuring the rv32emu with `ENABLE_JIT=1 ENABLE_EXT_M=0`. Can you provide more detailed testing steps?

**Comment by visitorckw** [comment]
> AFAIK, this error might happen when configuring the rv32emu with `ENABLE_JIT=1 ENABLE_EXT_M=0`. Can you provide more detailed testing steps?

Ah, I must have forgotten to run `make clean` to remove the previously compiled test executable, which caused the aforementioned error. After retesting, everything seems to be normal. Thanks.

**Comment by vacantron** [comment]
> > We might also want to bump the [reference device binary](https://github.com/sysprog21/rv32emu/blob/master/tests/arch-test-target/sail_cSim/riscv_sim_RV32).
> 
> @vacantron, can you rebuild `tests/arch-test-target/sail_cSim/riscv_sim_RV32` based on the latest [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test) and resolve the potential compliance issues? You can simply update [arch-test](https://github.com/vacantron/rv32emu/tree/arch-test) branch, so that I can cherry-pick git commits.

Done in ecf6f1e9b9ecd552145f1dc30d7b4c81320992f8.

**Pull request merged**
