### PR TITLE
Eliminate unused parameter warning

### PR DESCRIPTION
**Pull request by LambertWSJ**
set parameter to block map avoid to be unused

### CODE REVIEW

**Comment by jserv** [comment]
Use `git rebase -i` to squash. Read [How to Write a Git Commit Message](https://cbea.ms/git-commit/) carefully and refine your commit messages accordingly.

**Review by jserv — CHANGES_REQUESTED** [review]
Explain your motivation within commit message.

**Comment by jserv** [comment]
Always capitalize JIT if you refer it to just-in-time compilation.

**Comment by LambertWSJ** [comment]
Sorry, I shoud provide more info, I found this problem by compiler warning, the parameter bits is used for  construction block map.

**Pull request merged**
